<?php

namespace MediathaiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PanneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanneRepository extends EntityRepository
{
}
