<?php

namespace MediathaiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReparateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReparateurRepository extends EntityRepository
{
}
