<?php

namespace MediathaiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReparationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReparationRepository extends EntityRepository
{
}
