MediathaiBundle\Entity\Media:
    type: entity
    table: null
    repositoryClass: MediathaiBundle\Repository\MediaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        url:
            type: string
            length: 255
        alt:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
